language: node_js
node_js:
- '10'

cache:
  directories:
    - $HOME/.npm

install:
  - npm ci

script:
  - CI=false npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: 1/1B4M0a3WcdOtJPJ-UlaCYlsyubFze_tpWiq_JVlKBcE
